language: node_js
services:
  - docker
node_js:
  - 12
os:
  - linux
#  - osx
#osx_image: xcode11.3
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
script:
  - npm run build:web
jobs:
  include:
    - stage: test
      name: lint tests
      script: npm run lint
      os: linux

    - stage: test
      name: unit tests
      script: npm run test
      os: linux

    - stage: alpha
      name: publish alpha docker
      script: /bin/sh travis/docker.sh alpha
      if: branch = env(DEV_BRANCH) AND type = push
      os: linux

#     - stage: alpha
#       script: npm run release:all
#       name: build desktop artifacts
#       if: branch = env(DEV_BRANCH) AND type = push
#       os: linux

    - stage: release
      name: publish release docker
      script: /bin/sh travis/docker.sh release
      if: tag IS present
      os: linux

    - stage: release
      name: release desktop artifacts, tag and update version
      script: /bin/sh travis/release.sh
      if: branch = env(RELEASE_BRANCH) AND type = api AND commit_message = env(RELEASE_MESSAGE)
      os: linux
