trigger:
- master
- dev

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install and Build'

- task: Bash@3
  displayName: 'Get commit hash'
  inputs:
    targetType: 'inline'
    script: |
      GIT_COMMIT=$(git rev-parse --short HEAD)
      
      echo "GIT_COMMIT: ${GIT_COMMIT}"
      echo "##vso[task.setvariable variable=GIT_COMMIT]${GIT_COMMIT}"


- task: Docker@2
  displayName: 'Push and Build docker image'
  inputs:
    containerRegistry: 'dockerhub-superhow'
    repository: 'superhow/veritise-wallet'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(GIT_COMMIT)-$(Build.BuildId)
      latest

- task: CmdLine@2
  displayName: 'Replace kubernetes image tag'
  inputs:
    script: 'sed -i ''s/:latest/:$(GIT_COMMIT)-$(Build.BuildId)/g'' deployment.yml'
    workingDirectory: 'k8s'


- task: PublishBuildArtifacts@1
  displayName: 'Pusblish artifacts'
  inputs:
    PathtoPublish: 'k8s/deployment.yml'
    ArtifactName: 'drop'
    publishLocation: 'Container'

